name: CI
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  build:
    name: Add to Blocksky
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Run script
        run: yarn ts-node index.ts
        env:
          IDENTIFIER: ${{ secrets.IDENTIFIER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          LIST: ${{ secrets.LIST }}
